const channels = [
  
  {"name": "PROTV HD", "embed": "https://canale-tv.com/channel/pr0tv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "A1 HD", "embed": "https://canale-tv.com/channel/a1.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "TVR1", "embed": "https://canale-tv.com/channel/tvr1.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "TVR2", "embed": "https://canale-tv.com/channel/tvr2.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "CANAL D", "embed": "https://canale-tv.com/channel/canald.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "CANAL D2", "embed": "https://canale-tv.com/channel/canald2.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "PRIMA TV", "embed": "https://canale-tv.com/channel/primatv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "NATIONAL TV", "embed": "https://canale-tv.com/channel/nationaltv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "TVR 3", "embed": "https://canale-tv.com/channel/tvr3.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "TVR INTERNATIONAL", "embed": "https://canale-tv.com/channel/tvrinter.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "PROCINEMA", "embed": "https://canale-tv.com/channel/procinema.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "ACASA TV", "embed": "https://canale-tv.com/channel/acasatv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "ACASA GOLD", "embed": "https://canale-tv.com/channel/acasagold.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "ANTENA STARS", "embed": "https://canale-tv.com/channel/astars.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "NATIONAL 24 PLUS", "embed": "https://canale-tv.com/channel/national24plus.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "A3 CNN", "embed": "https://canale-tv.com/channel/a3cnn.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "ROMANIA TV", "embed": "https://canale-tv.com/channel/romaniatv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "REALITATEA TV", "embed": "https://canale-tv.com/channel/realitateatv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "PRIMA NEWS", "embed": "https://canale-tv.com/channel/primanews.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "B1 TV", "embed": "https://canale-tv.com/channel/b1tv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "EURONEWS ROMANIA", "embed": "https://canale-tv.com/channel/euronewsromnia.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "NEWS24", "embed": "https://canale-tv.com/channel/digi24.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "CNN", "embed": "https://canale-tv.com/channel/cnn.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "BBC NEWS", "embed": "https://canale-tv.com/channel/bbcnews.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "CBS REALITY", "embed": "https://canale-tv.com/channel/cbsreality.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "SUPERSPORT 1", "embed": "https://canale-tv.com/channel/dgsp1.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "SUPERSPORT 2", "embed": "https://canale-tv.com/channel/dgsp2.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "SUPERSPORT 3", "embed": "https://canale-tv.com/channel/dgsp3.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "SUPERSPORT 4", "embed": "https://canale-tv.com/channel/dgsp4.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "PRO ARENA", "embed": "https://canale-tv.com/channel/proarena.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "TVR SPORT", "embed": "https://canale-tv.com/channel/tvrsport.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "PRIMA SPORT 1", "embed": "https://canale-tv.com/channel/primasp1.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "PRIMA SPORT 2", "embed": "https://canale-tv.com/channel/primasp2.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "PRIMA SPORT 3", "embed": "https://canale-tv.com/channel/primasp3.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "PRIMA SPORT 4", "embed": "https://canale-tv.com/channel/primasp4.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "PRIMA SPORT 5", "embed": "https://canale-tv.com/channel/primasp5.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "PPV 1", "embed": "https://canale-tv.com/channel/ppv1.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "PPV 2", "embed": "https://canale-tv.com/channel/ppv2.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "PPV 3", "embed": "https://canale-tv.com/channel/ppv3.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "SPORT EXTRA", "embed": "https://canale-tv.com/channel/sportextra.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "EUR0SP0RT 1", "embed": "https://canale-tv.com/channel/eurosp1.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "EUR0SP0RT 2", "embed": "https://canale-tv.com/channel/eurosp2.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "HB0", "embed": "https://canale-tv.com/channel/hb.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "HB0 2", "embed": "https://canale-tv.com/channel/hb2.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "HB0 3", "embed": "https://canale-tv.com/channel/hb3.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "DIVA", "embed": "https://canale-tv.com/channel/diva.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "HAPPY TV", "embed": "https://canale-tv.com/channel/happy.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "FILM CAFE", "embed": "https://canale-tv.com/channel/filmcafe.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "TV 1000", "embed": "https://canale-tv.com/channel/tv1000.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "FlLM N0W", "embed": "https://canale-tv.com/channel/fnow.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "EPIC DRAMA", "embed": "https://canale-tv.com/channel/epdrama.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "AMC", "embed": "https://canale-tv.com/channel/amc.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "SH0WTIME 1", "embed": "https://canale-tv.com/channel/show1.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "SH0WTIME 2", "embed": "https://canale-tv.com/channel/show2.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "AXN HD", "embed": "https://canale-tv.com/channel/axn.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "AXN SPIN", "embed": "https://canale-tv.com/channel/axnspin.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "AXN BLACK", "embed": "https://canale-tv.com/channel/axnblack.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "AXN WHITE", "embed": "https://canale-tv.com/channel/axnwhite.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "CINEMAX", "embed": "https://canale-tv.com/channel/cmax.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "CINEMAX 2", "embed": "https://canale-tv.com/channel/cmax2.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "BOLYWOOD TV", "embed": "https://canale-tv.com/channel/bolywoodtv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "COMEDY CENTRAL", "embed": "https://canale-tv.com/channel/ccentral.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "WARNER TV", "embed": "https://canale-tv.com/channel/wornertv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "BBC FIRST", "embed": "https://canale-tv.com/channel/bfirst.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "MINIMAX", "embed": "https://canale-tv.com/channel/minimax.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "CARTOON NETWORK", "embed": "https://canale-tv.com/channel/cartoonnet.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "DISNEY CHANNEL", "embed": "https://canale-tv.com/channel/disneych.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "TEEN NICK", "embed": "https://canale-tv.com/channel/teennick.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "NICKELODEON", "embed": "https://canale-tv.com/channel/nickelodeon.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "DISNEY JR", "embed": "https://canale-tv.com/channel/disneyjr.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "CARTOONITO", "embed": "https://canale-tv.com/channel/cartonito.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "NICKTOONS", "embed": "https://canale-tv.com/channel/nicktoons.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "NICK JR", "embed": "https://canale-tv.com/channel/nickjr.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "JIM JAM", "embed": "https://canale-tv.com/channel/jimjam.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "DUCK TV", "embed": "https://canale-tv.com/channel/ducktv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "DISCOVERY CH", "embed": "https://canale-tv.com/channel/discoverych.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "HISTORY CHANNEL", "embed": "https://canale-tv.com/channel/historych.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "NAT GEO PEOPLE", "embed": "https://canale-tv.com/channel/netgeopeople.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "NATIONAL GEOGRAPHIC", "embed": "https://canale-tv.com/channel/natgeo.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "ID INVESTIGATION", "embed": "https://canale-tv.com/channel/idinvest.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "CRIME & INVESTIGATION", "embed": "https://canale-tv.com/channel/crimeinvest.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "TLC", "embed": "https://canale-tv.com/channel/tlc.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "NAT GEO WILD", "embed": "https://canale-tv.com/channel/natgeowild.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "BBC EARTH", "embed": "https://canale-tv.com/channel/bbcearth.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "VIASAT HISTORY", "embed": "https://canale-tv.com/channel/viahist.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "VIASAT NATURE", "embed": "https://canale-tv.com/channel/vianature.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "VIASAT EXPLORER", "embed": "https://canale-tv.com/channel/viaexplorer.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "TRAVEL MIX", "embed": "https://canale-tv.com/channel/travelmix.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "PAPRIKA", "embed": "https://canale-tv.com/channel/paprika.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "HGTV", "embed": "https://canale-tv.com/channel/hgtv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "TARAF TV", "embed": "https://canale-tv.com/channel/taraf.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "FAVORIT TV", "embed": "https://canale-tv.com/channel/favorit.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "ETNO TV", "embed": "https://canale-tv.com/channel/etno.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "HIT MUSIC", "embed": "https://canale-tv.com/channel/hitmusic.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "BALCAN MUSIC", "embed": "https://canale-tv.com/channel/balcanmuz.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "UTV", "embed": "https://canale-tv.com/channel/utv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "KISS TV", "embed": "https://canale-tv.com/channel/kisstv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "MUSIC CHANNEL", "embed": "https://canale-tv.com/channel/musicch.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "ZU TV", "embed": "https://canale-tv.com/channel/zutv.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "Fish & Hunting TV", "embed": "https://canale-tv.com/channel/fishy.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "F1lm B0X", "embed": "https://canale-tv.com/channel/fbox1.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "F1lm B0X Extra", "embed": "https://canale-tv.com/channel/fbox-extra.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "F1lm B0X Premium", "embed": "https://canale-tv.com/channel/fbox-premium.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "Canal 33", "embed": "https://canale-tv.com/channel/canal-33.html", "category": "Canale TV ROMANIA Embed", "country": "RO"},
  {"name": "Dizi", "embed": "https://canale-tv.com/channel/dizy.html", "category": "Canale TV ROMANIA Embed", "country": "RO"}
]
